
version: "3.9"
   
services:
  
  db:
    image: postgres
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"
  

  webapp:
    build: .
    container_name: django-app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn project.wsgi -b 0.0.0.0:8000"
    expose:
      - "8000"
    depends_on:
      - db
    env_file: 
      - ./config/.env


  nginx:
    image: nginx
    container_name: ngx
    ports: 
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./notes/static:/static
    depends_on: 
      - webapp

volumes:
  postgres_data:

    